name: password_generator_demo
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  #state management
  flutter_mobx: ^2.0.6+1
  mobx: ^2.0.7+5

  #codegen
  mobx_codegen: ^2.0.7
  build_runner: ^2.2.0

  url_launcher: ^6.1.5

  #localization
  easy_localization: ^3.0.1


  #app icons
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.7
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons: 
  android: true
  ios: true
  image_path: "assets/icons/generator_app_icon.png"
  adaptive_icon_background: "#1E1B16"
  adaptive_icon_foreground: "assets/icons/generator_app_icon_foreground.png"

flutter_native_splash:
  android: true
  ios: true
  android12: true
  color: "#1E1B16"
  image: assets/icons/generator_app_icon.png
  


flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf

