name: password_generator
version: 1.0.3

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  #state management
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1

  #core
  equatable: ^2.0.5

  #utility
  url_launcher: ^6.1.5

  #localization
  easy_localization: ^3.0.1

  #routing
  auto_route: ^5.0.1


  #app icons
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  #code gen
  build_runner: ^2.2.0
  auto_route_generator: ^5.0.1

flutter_icons: 
  android: true
  ios: true
  image_path: "assets/icons/generator_app_icon.png"
  adaptive_icon_background: "#1E1B16"
  adaptive_icon_foreground: "assets/icons/generator_app_icon_foreground.png"

flutter_native_splash:
  android: true
  ios: true
  android12: true
  color: "#1E1B16"
  image: assets/icons/generator_app_icon.png
  


flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf

