name: password_generator
version: 1.0.6+7

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #state management
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2

  #utility
  share_plus: ^7.0.2
  in_app_review: ^2.0.6
  url_launcher: ^6.1.12
  path_provider: ^2.0.15
  

  #localization
  easy_localization: ^3.0.2

  #routing
  auto_route: ^7.7.1

  #functional programming
  dartz: ^0.10.1

  #code gen
  freezed_annotation: ^2.4.1

  #app icons
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  #linter
  very_good_analysis: ^5.0.0+1

  #code gen
  freezed: ^2.4.1
  build_runner: ^2.4.6
  auto_route_generator: ^7.2.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/generator_app_icon.png"
  adaptive_icon_background: "#1E1B16"
  adaptive_icon_foreground: "assets/icons/generator_app_icon_foreground.png"

flutter_native_splash:
  android: true
  ios: true
  android12: true
  color: "#1E1B16"
  image: assets/icons/generator_app_icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/icons/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
