name: password_generator
version: 1.1.2+20

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #state management
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.4

  # caching
  hive_flutter: ^1.1.0

  # firebase
  firebase_core: ^2.27.1
  firebase_crashlytics: ^3.4.19

  #utility
  crypto: ^3.0.3
  envied: ^0.5.3
  logger: ^2.2.0
  share_plus: ^7.2.1
  in_app_review: ^2.0.8
  url_launcher: ^6.2.2
  path_provider: ^2.1.1
  package_info_plus: ^6.0.0

  #localization
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.5

  #routing
  auto_route: ^7.8.4

  #functional programming
  fpdart: ^1.1.0

  #code gen
  freezed_annotation: ^2.4.1

  #app icons
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  #linter
  very_good_analysis: ^5.1.0

  #code gen
  freezed: ^2.4.5
  build_runner: ^2.4.7
  envied_generator: ^0.5.3
  auto_route_generator: ^7.3.2

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21
  image_path: "assets/icons/generator_app_icon.png"
  adaptive_icon_background: "#1E1B16"
  adaptive_icon_foreground: "assets/icons/generator_app_icon_foreground.png"

flutter_native_splash:
  android: true
  ios: true
  color: "#1E1B16"
  image: assets/icons/generator_app_icon.png

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
